server {
    listen 80;
    listen [::]:80;

    server_name mailpit.test;

    location / {
        proxy_pass http://mailpit:8025;
        include /usr/local/openresty/nginx/conf/sites-available/snippets/proxy.conf;
        include /usr/local/openresty/nginx/conf/sites-available/snippets/websocket.conf;
    }
}
