server {
    listen 80;
    listen [::]:80;

    server_name phpmyadmin.test;

    location / {
        proxy_pass http://phpmyadmin:80;
        include /usr/local/openresty/nginx/conf/sites-available/snippets/proxy.conf;
    }
}
